services:
  db:
    image: mysql:8.0
    container_name: referral_db
    restart: always
    environment:
      MYSQL_DATABASE: referral_db
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: referral_backend
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - MYSQLHOST=autorack.proxy.rlwy.net
      - MYSQLPORT=46431
      - MYSQLUSER=root
      - MYSQLPASSWORD=nKnUUyMLBGLhlpIhLfZsWHSHvjmWVvpG
      - MYSQLDATABASE=railway
      - VITE_API_URL=http://localhost:8080/api

  frontend:
    build: ./frontend
    container_name: referral_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "5173:80"
    environment:
      - VITE_API_URL=http://localhost:8080/api
