# spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/referral_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

Custom properties
referral.jwt.secret=9a4f2c8d3b7e1f6g5h4i3j2k1l0m9n8o7p6q5r4s3t2u1v0wxy
referral.jwt.expiration=86400000
